ALTER TABLE tasks ADD COLUMN total_input_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN total_output_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN total_cache_read_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN estimated_cost_usd REAL NOT NULL DEFAULT 0.0;
ALTER TABLE tasks ADD COLUMN turn_count INTEGER NOT NULL DEFAULT 0;
