//! Auto credential helper for the terminal's `git`.
//!
//! The connected GitHub token lives in the app (and is used by Rustic's own
//! git commands), but a raw `git` invoked in a user terminal knows nothing about
//! it and prompts interactively — which fails since GitHub dropped password
//! auth. This module bridges that gap by writing a tiny `GIT_ASKPASS` script and
//! exporting the token into the server process environment. Terminals inherit
//! that environment at spawn (the same mechanism that gives them `PATH`), so
//! `git clone/fetch/push` against github.com "just works" with no prompt.
//!
//! Scope: the askpass script only answers for `github.com`, so the token never
//! leaks to other remotes (those fall back to git's own prompt/helpers).

use std::path::Path;

const ASKPASS_SH: &str = r#"#!/bin/sh
# Auto-generated by Rustic. Answers git's HTTPS credential prompts for
# github.com using the token connected in the app. Username is irrelevant to
# GitHub when the password is a valid token, so any non-empty value works.
# Non-GitHub hosts are intentionally left unanswered.
case "$1" in
  *github.com*)
    case "$1" in
      *[Uu]sername*) printf '%s\n' "${GIT_ASKPASS_USER:-x-access-token}" ;;
      *)             printf '%s\n' "${GIT_ASKPASS_TOKEN}" ;;
    esac
    ;;
esac
"#;

/// Install or clear the terminal git-credential environment from the currently
/// connected token. Safe to call repeatedly; only terminals spawned *after* the
/// call see the change (already-open shells keep the env they were spawned with).
pub fn apply(data_dir: &Path, token: Option<&str>) {
    match token {
        Some(t) if !t.trim().is_empty() => {
            let script = data_dir.join("git-askpass.sh");
            if let Err(e) = std::fs::write(&script, ASKPASS_SH) {
                tracing::warn!(error = %e, "could not write git askpass script; terminal git auth disabled");
                return;
            }
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let _ = std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o700));
            }
            std::env::set_var("GIT_ASKPASS", &script);
            std::env::set_var("GIT_ASKPASS_USER", "x-access-token");
            std::env::set_var("GIT_ASKPASS_TOKEN", t);
            // Convenience for the `gh` CLI and other tooling that reads these.
            std::env::set_var("GITHUB_TOKEN", t);
            std::env::set_var("GH_TOKEN", t);
            tracing::info!("terminal git credential helper installed for github.com");
        }
        _ => {
            for k in [
                "GIT_ASKPASS",
                "GIT_ASKPASS_USER",
                "GIT_ASKPASS_TOKEN",
                "GITHUB_TOKEN",
                "GH_TOKEN",
                "GIT_AUTHOR_NAME",
                "GIT_AUTHOR_EMAIL",
                "GIT_COMMITTER_NAME",
                "GIT_COMMITTER_EMAIL",
            ] {
                std::env::remove_var(k);
            }
        }
    }
}

/// Export the git commit identity (author + committer) into the server process
/// env so headless commits have a valid author instead of failing with
/// "unknown identity". Inherited by every `git` Rustic spawns, exactly like the
/// askpass vars. Cleared by `apply(.., None)` on logout/token-clear.
pub fn set_identity(name: &str, email: &str) {
    std::env::set_var("GIT_AUTHOR_NAME", name);
    std::env::set_var("GIT_AUTHOR_EMAIL", email);
    std::env::set_var("GIT_COMMITTER_NAME", name);
    std::env::set_var("GIT_COMMITTER_EMAIL", email);
    tracing::info!(name = %name, email = %email, "git commit identity installed");
}
